"""Generate rtl_airband.conf and supervise rtl_airband subprocess."""

from __future__ import annotations

import logging
import os
import signal
import subprocess
import tempfile
from pathlib import Path

from airband.config import Config
from airband.planner.channels import PlannedChannel

log = logging.getLogger(__name__)


def render_conf(cfg: Config, channels: list[PlannedChannel], conf_path: Path) -> None:
    if not channels:
        raise ValueError("no channels to render")

    freqs = [ch.freq_mhz for ch in channels]
    center = sum(freqs) / len(freqs)
    use_scan = any(ch.mode == "scan" for ch in channels) and len(channels) > 1
    mode = "scan" if use_scan else "multichannel"

    ch_blocks: list[str] = []
    for ch in channels:
        outputs = [
            f"""        {{
          type = "udp_stream";
          dest_address = "127.0.0.1";
          dest_port = {ch.udp_port};
          continuous = false;
        }}"""
        ]
        if cfg.record.enabled:
            safe = ch.label.replace(" ", "_").replace('"', "")[:32] or f"{ch.freq_mhz:.3f}"
            outputs.append(
                f"""        {{
          type = "file";
          directory = "{cfg.archive_dir / 'rtl_airband'}";
          filename_template = "{safe}";
          continuous = false;
        }}"""
            )
        ch_blocks.append(
            f"""    {{
      freq = {ch.freq_mhz:.3f};
      modulation = "am";
      outputs: (
{",".join(outputs)}
      );
    }}"""
        )

    scan_line = ""
    if use_scan:
        scan_freqs = ", ".join(f"{ch.freq_mhz:.3f}" for ch in channels)
        scan_line = f"\n  scanfreqs = ({scan_freqs});\n  squelch_threshold = -50;\n"

    text = f"""# Generated by kingfisher-airband — do not edit
devices: ({{
  type = "rtlsdr";
  gain = {cfg.sdr.gain};
  correction = {cfg.sdr.correction_ppm};
  centerfreq = {center:.3f};
  mode = "{mode}";
{scan_line}  channels: (
{",".join(ch_blocks)}
  );
}});
"""
    conf_path.parent.mkdir(parents=True, exist_ok=True)
    conf_path.write_text(text)
    log.info("wrote rtl_airband config %s (%d channels, mode=%s)", conf_path, len(channels), mode)


class RTLAirbandProcess:
    def __init__(self, cfg: Config) -> None:
        self._cfg = cfg
        self._proc: subprocess.Popen[bytes] | None = None
        self._conf_path: Path | None = None

    @property
    def running(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    def start(self, channels: list[PlannedChannel]) -> None:
        self.stop()
        if not self._cfg.sdr.enabled:
            log.info("SDR disabled in config")
            return
        bin_path = Path(self._cfg.sdr.rtl_airband_bin)
        if not bin_path.is_file():
            log.warning("rtl_airband not found at %s — SDR capture disabled", bin_path)
            return

        fd, tmp = tempfile.mkstemp(prefix="rtl_airband_", suffix=".conf")
        os.close(fd)
        self._conf_path = Path(tmp)
        render_conf(self._cfg, channels, self._conf_path)
        (self._cfg.archive_dir / "rtl_airband").mkdir(parents=True, exist_ok=True)

        self._proc = subprocess.Popen(
            [str(bin_path), "-f", "-c", str(self._conf_path)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        log.info("started rtl_airband pid=%s", self._proc.pid)

    def stop(self) -> None:
        if self._proc is not None and self._proc.poll() is None:
            self._proc.send_signal(signal.SIGTERM)
            try:
                self._proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._proc.kill()
        self._proc = None
        if self._conf_path and self._conf_path.is_file():
            try:
                self._conf_path.unlink()
            except OSError:
                pass
            self._conf_path = None
