"""Generate rtl_airband.conf and supervise rtl_airband subprocess."""

from __future__ import annotations

import logging
import os
import signal
import subprocess
import threading
import tempfile
from pathlib import Path

from airband.config import Config
from airband.planner.channels import RadioPlan

log = logging.getLogger(__name__)


def _file_output(cfg: Config, template: str) -> str:
    return f"""        {{
          type = "file";
          directory = "{cfg.archive_dir / 'rtl_airband'}";
          filename_template = "{template}";
          continuous = false;
        }}"""


def _udp_output(port: int) -> str:
    return f"""        {{
          type = "udp_stream";
          dest_address = "127.0.0.1";
          dest_port = {port};
          continuous = false;
        }}"""


def render_conf(cfg: Config, plan: RadioPlan, conf_path: Path) -> None:
    if not plan.channels:
        raise ValueError("no channels to render")

    index_line = f"  index = {cfg.sdr.index};\n"
    squelch = cfg.sdr.squelch_snr_threshold
    archive = cfg.archive_dir / "rtl_airband"

    if plan.is_scan:
        freqs = ", ".join(f"{ch.freq_mhz:.3f}" for ch in plan.channels)
        labels = ", ".join(f'"{ch.label}"' for ch in plan.channels)
        port = plan.channels[0].udp_port
        outputs = [_udp_output(port)]
        if cfg.record.enabled:
            outputs.append(_file_output(cfg, "scan"))
        text = f"""# Generated by kingfisher-airband — do not edit
devices: ({{
  type = "rtlsdr";
  gain = {cfg.sdr.gain};
  correction = {cfg.sdr.correction_ppm};
{index_line}  mode = "scan";
  channels: (
    {{
      freqs = ( {freqs} );
      labels = ( {labels} );
      modulation = "am";
      squelch_snr_threshold = {squelch};
      outputs: (
{",".join(outputs)}
      );
    }}
  );
}});
"""
    else:
        freqs = [ch.freq_mhz for ch in plan.channels]
        center = sum(freqs) / len(freqs)
        ch_blocks: list[str] = []
        for ch in plan.channels:
            outputs = [_udp_output(ch.udp_port)]
            if cfg.record.enabled:
                safe = ch.label.replace(" ", "_").replace('"', "")[:32] or f"{ch.freq_mhz:.3f}"
                outputs.append(_file_output(cfg, safe))
            ch_blocks.append(
                f"""    {{
      freq = {ch.freq_mhz:.3f};
      modulation = "am";
      squelch_snr_threshold = {squelch};
      outputs: (
{",".join(outputs)}
      );
    }}"""
            )
        text = f"""# Generated by kingfisher-airband — do not edit
devices: ({{
  type = "rtlsdr";
  gain = {cfg.sdr.gain};
  correction = {cfg.sdr.correction_ppm};
{index_line}  centerfreq = {center:.3f};
  mode = "multichannel";
  channels: (
{",".join(ch_blocks)}
  );
}});
"""
    conf_path.parent.mkdir(parents=True, exist_ok=True)
    conf_path.write_text(text)
    archive.mkdir(parents=True, exist_ok=True)
    log.info(
        "wrote rtl_airband config %s (%s, %d freqs)",
        conf_path,
        plan.mode,
        len(plan.channels),
    )


class RTLAirbandProcess:
    def __init__(self, cfg: Config) -> None:
        self._cfg = cfg
        self._proc: subprocess.Popen[bytes] | None = None
        self._conf_path: Path | None = None
        self._last_error: str = ""

    @property
    def running(self) -> bool:
        self._reap()
        return self._proc is not None

    @property
    def last_error(self) -> str:
        return self._last_error

    def _reap(self) -> None:
        if self._proc is None:
            return
        code = self._proc.poll()
        if code is None:
            return
        err = ""
        if self._proc.stderr:
            try:
                err = self._proc.stderr.read().decode(errors="replace").strip()
            except Exception:
                pass
        self._last_error = err or f"rtl_airband exited with code {code}"
        log.error("rtl_airband died: %s", self._last_error[-500:])
        self._proc = None

    def _drain_stderr(self) -> None:
        proc = self._proc
        if proc is None or proc.stderr is None:
            return
        for line in proc.stderr:
            text = line.decode(errors="replace").rstrip()
            if text:
                log.info("rtl_airband: %s", text)

    def start(self, plan: RadioPlan) -> None:
        self.stop()
        self._last_error = ""
        if not self._cfg.sdr.enabled:
            log.info("SDR disabled in config")
            return
        bin_path = Path(self._cfg.sdr.rtl_airband_bin)
        if not bin_path.is_file():
            msg = f"rtl_airband not found at {bin_path}"
            self._last_error = msg
            log.warning("%s — SDR capture disabled", msg)
            return

        fd, tmp = tempfile.mkstemp(prefix="rtl_airband_", suffix=".conf")
        os.close(fd)
        self._conf_path = Path(tmp)
        render_conf(self._cfg, plan, self._conf_path)

        self._proc = subprocess.Popen(
            [str(bin_path), "-f", "-c", str(self._conf_path)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )
        threading.Thread(target=self._drain_stderr, name="rtl-airband-stderr", daemon=True).start()
        log.info("started rtl_airband pid=%s mode=%s", self._proc.pid, plan.mode)
        # Fail fast if config is rejected immediately.
        import time

        time.sleep(0.5)
        self._reap()
        if self._proc is None:
            log.error("rtl_airband failed to start — check config and dongle access")

    def stop(self) -> None:
        if self._proc is not None and self._proc.poll() is None:
            self._proc.send_signal(signal.SIGTERM)
            try:
                self._proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._proc.kill()
                self._proc.wait(timeout=2)
        self._reap()
        self._proc = None
        if self._conf_path and self._conf_path.is_file():
            try:
                self._conf_path.unlink()
            except OSError:
                pass
            self._conf_path = None
